<?
/*
    phpCodeGenie Language File
    Language : English
    Date   : 02/04/2003
    Author : Nilesh Dosooye
*/

$langActiveDb = "Active Database";
$langActiveTable = "Active Table";

$langChooseDbTable = "Please click on the + sign and choose a Table on the left";

$langFormMaker = "Code Genie Form Maker  ";
$langFormMakerDesc = "This utility will build a form for you from a MySql Database Table. You can choose which form element you want for each field in your database. The form element names will be named the same name as your field with '$stringToAppendToField' appended to the end. This utility will build source code for the form and show you a preview of how it looks like. Use it in conjunction with the Insert Builder to have a complete automated way to insert data to your database.";

$langInsertQueryBuilder = "Insert Query Builder";
$langInsertQueryBuilderDesc = "This utility will build a MySql insert query for you from a MySql Database Table. Used in conjuntion with the Form Maker, the Insert Query Buiilder will generate your insert statement for all fields in your MySql Database. The variable names used to build the insert query will have the same name as the fields with '$stringToAppendToField' appended at the end.";
 
$langDbLister = "Database Lister";
$langDbListerDesc = "This utility will generate code for you that will list every row with all of its fields in your MySQL Database Table. Each alternate row will be differently color coded and also will have Edit and Delete Buttons. The Edit Button should be used in conjunction with the Update Form Builder.";
 
$langEditFormMaker = "Edit/Update Form Builder";
$langEditFormMakerDesc = "This utility will generate code to build a form for you from which you can update existing data. From other preexisting scripts, such as the one generated from Database Lister, you will need to pass the Primary Key of your table to this script which will in turn get all the data and pre-populate your form for you for Editing. Use it in conjunction with the Update Query Maker to do the updates on your data. Use the code generated by the Update Query Maker, as the Form Action Script.";
 
$langUpdateMaker = "Update Maker";
$langUpdateMakerDesc = "This utility will generate code to update data in your MySQL Database. Use it as the Form Action script, of the Edit/Update Form maker.";
 
$langViewMaker = "View Maker";
$langViewMakerDesc = "This utility will generate code for a view details page for a record.";
 
$langDeleteConfirmationMaker = "Delete Confirmation Maker";
$langDeleteConfirmationMakerDesc = "This utility will generate code to show user the record they want to delete and ask for their confirmation before deleting it.";
 
$langDeleteScriptMaker = "Delete Script Maker";
$langDeleteScriptMakerDesc = "This utility will generate code to delete a record after the confirmation page.";
 
$langSearchFormMaker = "Search Form Maker";
$langSearchFormMakerDesc = "This utility will generate code for a Search Form.";
 
$langSearchScriptMaker = "Search Script Maker";
$langSearchScriptMakerDesc = "This utility will generate the script that will search the database.";
 
$langDropDownMaker = "Drop Down/Multiple Select/Radio Button/Check Box Code Maker";
$langDropDownMakerDesc = "This utility will code that will build a drop down menu.";
 
 
$x = "Choose Fields and Form Element Types that you want your Data Entry Form to have for table groups";
$x = "Enter a";



// Generic Text

$langFieldName = " Field Name";
$langFieldType = " Field Type";
$langSubmit = " Submit ";
$langReset = " Reset";

$langFTextField = "Text Field";
$langFPassword = "Password";
$langFTextArea = "Text Area";
$langFCheckBox = "Check Box";
$langFRadioButton = "Radio Button";
$langFListMenu = "List Menu";
$langFMultipleList = "Multiple List";
$langFFileUpload = "File Uploads";
$langNone = "NONE";


?>